### ISSUE TITLE
Large 2d map chunking

### ISSUE THREAD

**Issue by HawkeRPG** [gotenxds/Redrook#1]
I saw your post from 2019 about very large tilemaps [https://github.com/Unity-Technologies/2d-extras/issues/86](url) and I am looking to do something similar. About 40k x 30k tiles total (big dream that might not even achieve). Would be too many subscenes if I used DOTS (tilemaps dont work with it anyway so each tile would need to be a seperate entity). Was wondering if you managed to find an efficient way you would be willing to share? I am assuming you were working on that for this project. Is this still in development?

**Comment by gotenxds** [comment]
Hya @HawkeRPG, this project is not development as of right now, we moved on to something smaller and a bit different, also a 2d tilemap openworld but much smaller.

I have found multiple ways of achieving this, one of them is in this project, I dont remember exactly where but feel free to dig into the GridLoading folder as all of the logic is there.

Generally I used flat buffers to save the world data and I loaded it all quickly setting the tiles at a radius around the player as they moved.

The second way (which I am using in our current project Moonbell) is splitting the world into smallish chunks and loading them dynamically with addreasables 
Here is how it looks like

https://github.com/gotenxds/Redrook/assets/3519520/f2e6b73d-4b15-4601-a058-1cf71f12e785


Feel free to jump to our new projects discord and send me a pm if you need help https://discord.gg/nNyHCNBe
